const MODS_DATA = [
    { name: "Fabric API", file: "fabric-api-0.138.4+1.21.10.jar", category: "library", deps: [], depBy: ["Amendments", "Balm", "Better Combat", "Cardinal Components API", "Carry On", "Continuity", "Decorative Blocks", "Entity Culling", "FallingTree", "Forge Config API Port", "Gliding", "IMBlocker", "Inventory Profiles Next", "Jade", "JourneyMap", "Leawind's Third Person", "libIPN", "LotTweaks", "Mod Menu", "Moonlight Lib", "PandaLib", "Player Animation Library", "Roughly Enough Items", "Supplementaries", "Traveler's Backpack", "Waystones", "Windchimes", "WorldEditCUI"], desc: "Fabric 模组开发的核心 API 库", mcVersion: "1.21.10" },
    { name: "Architectury API", file: "architectury-18.0.8-fabric.jar", category: "library", deps: [], depBy: ["Roughly Enough Items", "Leawind's Third Person"], desc: "跨平台模组开发 API", mcVersion: "1.21+" },
    { name: "Balm", file: "balm-fabric-1.21.10-21.10.10.jar", category: "library", deps: ["Fabric API"], depBy: ["Waystones"], desc: "多加载器模组抽象层", mcVersion: "1.21.10" },
    { name: "Cardinal Components API", file: "cardinal-components-api-7.2.0.jar", category: "library", deps: ["Fabric API"], depBy: ["Traveler's Backpack"], desc: "为游戏对象附加数据的 API", mcVersion: "1.21+" },
    { name: "Cloth Config API", file: "cloth-config-20.0.149-fabric.jar", category: "library", deps: [], depBy: ["Better Combat"], desc: "模组配置界面 API", mcVersion: "1.21+" },
    { name: "Fabric Language Kotlin", file: "fabric-language-kotlin-1.13.8+kotlin.2.3.0.jar", category: "library", deps: [], depBy: ["libIPN"], desc: "支持 Kotlin 语言的 Fabric 模组", mcVersion: "1.21+" },
    { name: "Forge Config API Port", file: "ForgeConfigAPIPort-v21.10.1+mc1.21.10-Fabric.jar", category: "library", deps: ["Fabric API"], depBy: [], desc: "Forge 配置系统移植到 Fabric", mcVersion: "1.21.10" },
    { name: "libIPN", file: "libIPN-fabric-1.21.10-6.6.2.jar", category: "library", deps: ["Fabric API", "Fabric Language Kotlin"], depBy: ["Inventory Profiles Next"], desc: "Inventory Profiles Next 的库模组", mcVersion: "1.21.10" },
    { name: "MaLiLib", file: "malilib-fabric-1.21.10-0.26.8.jar", category: "library", deps: [], depBy: ["Litematica", "Tweakeroo"], desc: "masa 客户端模组的库", mcVersion: "1.21.10" },
    { name: "Moonlight Lib", file: "moonlight-1.21-2.29.9-fabric.jar", category: "library", deps: ["Fabric API"], depBy: ["Amendments", "Supplementaries"], desc: "轻量级工具库，包含村民 AI、地图标记等", mcVersion: "1.21" },
    { name: "PandaLib", file: "pandalib-fabric-1.21.10-1.0.0-ALPHA.2.1.jar", category: "library", deps: ["Fabric API"], depBy: ["FallingTree"], desc: "The Panda Oliver 的库模组", mcVersion: "1.21.10" },
    { name: "Player Animation Library", file: "PlayerAnimationLibFabric-1.1.3+mc.1.21.9.jar", category: "library", deps: ["Fabric API"], depBy: [], desc: "无冲突的玩家动画支持库", mcVersion: "1.21.9" },
    { name: "Sodium", file: "sodium-fabric-0.7.3+mc1.21.10.jar", category: "optimization", deps: [], depBy: ["Indium", "Iris", "Reese's Sodium Options", "Sodium Extra", "Supplementaries"], desc: "最快的渲染优化模组", mcVersion: "1.21.10" },
    { name: "Indium", file: "indium-1.0.35+mc1.21.jar", category: "optimization", deps: ["Sodium"], depBy: ["Supplementaries"], optional: ["Continuity"], desc: "Sodium 的 Fabric 渲染 API 兼容层", mcVersion: "1.21" },
    { name: "Iris Shaders", file: "iris-fabric-1.9.7+mc1.21.10.jar", category: "optimization", deps: ["Sodium"], depBy: [], optional: ["Reese's Sodium Options", "Sodium Extra"], desc: "兼容 Optifine 光影的现代光影模组", mcVersion: "1.21.10" },
    { name: "Reese's Sodium Options", file: "reeses-sodium-options-fabric-1.8.6+mc1.21.10.jar", category: "optimization", deps: ["Sodium"], depBy: [], optional: ["Sodium Extra", "Iris"], desc: "Sodium 的替代选项菜单", mcVersion: "1.21.10" },
    { name: "Sodium Extra", file: "sodium-extra-fabric-0.7.1+mc1.21.10.jar", category: "optimization", deps: ["Sodium"], depBy: [], optional: ["Reese's Sodium Options", "Iris"], desc: "Sodium 的额外功能和自定义", mcVersion: "1.21.10" },
    { name: "Continuity", file: "continuity-3.0.1-beta.2+1.21.10.jar", category: "optimization", deps: ["Fabric API"], depBy: [], optional: ["Indium"], desc: "高效的连接材质支持", mcVersion: "1.21.10" },
    { name: "Entity Culling", file: "entityculling-fabric-1.9.5-mc1.21.10.jar", category: "optimization", deps: ["Fabric API"], depBy: [], desc: "隐藏不可见实体以提升性能", mcVersion: "1.21.10" },
    { name: "Lithium", file: "lithium-fabric-0.20.1+mc1.21.10.jar", category: "optimization", deps: [], depBy: [], desc: "游戏逻辑优化模组", mcVersion: "1.21.10" },
    { name: "ModernFix", file: "modernfix-fabric-latest.jar", category: "optimization", deps: [], depBy: [], desc: "一体化性能优化和错误修复", mcVersion: "1.21+" },
    { name: "Amendments", file: "amendments-1.21-2.0.14-fabric.jar", category: "gameplay", deps: ["Fabric API", "Moonlight Lib"], depBy: [], desc: "调整原版方块功能和视觉效果", mcVersion: "1.21" },
    { name: "Better Combat", file: "bettercombat-fabric-3.0.0+1.21.10.jar", category: "gameplay", deps: ["Fabric API", "Cloth Config API"], depBy: [], desc: "类似地下城的近战战斗系统", mcVersion: "1.21.10" },
    { name: "Carry On", file: "carryon-fabric-1.21.9-2.8.0.jar", category: "gameplay", deps: ["Fabric API"], depBy: [], desc: "拾起并搬运方块实体和生物", mcVersion: "1.21.9" },
    { name: "FallingTree", file: "fallingtrees-fabric-1.21.10-0.14.0-APLHA.2.1.jar", category: "gameplay", deps: ["Fabric API", "PandaLib"], depBy: [], desc: "砍伐一部分即可砍倒整棵树", mcVersion: "1.21.10" },
    { name: "Supplementaries", file: "supplementaries-1.21-3.5.16-fabric.jar", category: "gameplay", deps: ["Moonlight Lib", "Fabric API", "Indium", "Sodium"], depBy: [], desc: "香草风格装饰和功能性方块", mcVersion: "1.21" },
    { name: "Traveler's Backpack", file: "travelersbackpack-fabric-1.21.10-10.10.4.jar", category: "gameplay", deps: ["Fabric API", "Cardinal Components API"], depBy: [], desc: "独特的可升级背包系统", mcVersion: "1.21.10" },
    { name: "Waystones", file: "waystones-fabric-1.21.10-21.10.5.jar", category: "gameplay", deps: ["Fabric API", "Balm"], depBy: [], desc: "传送回已激活的路标", mcVersion: "1.21.10" },
    { name: "Gliding", file: "gliding-1.1.0.jar", category: "gameplay", deps: ["Fabric API"], depBy: [], desc: "可制作的滑翔翼", mcVersion: "1.21+" },
    { name: "Leawind's Third Person", file: "leawind_third_person-2.3.0-mc1.21-1.21.1-fabric.jar", category: "gameplay", deps: ["Fabric API", "Architectury API"], depBy: [], desc: "实用流畅的第三人称视角", mcVersion: "1.21-1.21.1" },
    { name: "Windchimes", file: "windchimes-1.7.1-1.21.10.jar", category: "decoration", deps: ["Fabric API"], depBy: [], desc: "装饰性风铃和环境音效", mcVersion: "1.21.10" },
    { name: "Decorative Blocks", file: "Decorative Blocks-Fabric-1.20.4-5.0.2.jar", category: "decoration", deps: ["Fabric API"], depBy: [], warning: "版本 1.20.4，可能不兼容 1.21.10", desc: "各种装饰性方块", mcVersion: "1.20.4" },
    { name: "Entity Model Features", file: "entity_model_features_1.21.9-fabric-3.0.10.jar", category: "decoration", deps: ["Entity Texture Features"], depBy: [], desc: "OptiFine 格式的自定义实体模型", mcVersion: "1.21.9" },
    { name: "Entity Texture Features", file: "entity_texture_features_1.21.9-fabric-7.0.8.jar", category: "decoration", deps: [], depBy: ["Entity Model Features"], desc: "实体发光、随机和自定义纹理", mcVersion: "1.21.9" },
    { name: "Litematica", file: "litematica-fabric-1.21.10-0.24.7.jar", category: "utility", deps: ["MaLiLib"], depBy: [], desc: "客户端原理图和建筑工具", mcVersion: "1.21.10" },
    { name: "IMBlocker", file: "IMBlocker-6.0.3-fabric-1.21.9+.jar", category: "utility", deps: ["Fabric API"], depBy: [], desc: "自动切换输入法", mcVersion: "1.21.9+" },
    { name: "Inventory Profiles Next", file: "InventoryProfilesNext-fabric-1.21.10-2.2.3.jar", category: "utility", deps: ["Fabric API", "libIPN"], depBy: [], desc: "高级物品栏管理和排序", mcVersion: "1.21.10" },
    { name: "Jade", file: "Jade-1.21.9-Fabric-20.1.0.jar", category: "utility", deps: ["Fabric API"], depBy: [], desc: "查看方块和实体信息", mcVersion: "1.21.9" },
    { name: "JourneyMap", file: "journeymap-fabric-1.21.10-6.0.0-beta.54.jar", category: "utility", deps: ["Fabric API"], depBy: [], desc: "实时地图显示", mcVersion: "1.21.10" },
    { name: "LotTweaks", file: "LotTweaks-mc1.21.10-fabric-2.3.6.jar", category: "utility", deps: ["Fabric API"], depBy: [], desc: "建造者生产力调整", mcVersion: "1.21.10" },
    { name: "Mod Menu", file: "modmenu-16.0.0.jar", category: "utility", deps: ["Fabric API"], depBy: [], desc: "模组列表菜单", mcVersion: "1.21+" },
    { name: "Roughly Enough Items", file: "RoughlyEnoughItems-21.9.812-fabric.jar", category: "utility", deps: ["Fabric API", "Architectury API"], depBy: [], desc: "简洁的合成配方查看器", mcVersion: "1.21.9" },
    { name: "Tweakeroo", file: "tweakeroo-fabric-1.21.10-0.26.5.jar", category: "utility", deps: ["MaLiLib"], depBy: [], desc: "各种客户端调整和快捷功能", mcVersion: "1.21.10" },
    { name: "WorldEdit", file: "worldedit-mod-7.4.0-beta-01.jar", category: "utility", deps: [], depBy: ["WorldEditCUI"], desc: "游戏内地图编辑器", mcVersion: "1.21+" },
    { name: "WorldEditCUI", file: "WorldEditCUI-1.21.10+01.jar", category: "utility", deps: ["Fabric API", "WorldEdit"], depBy: [], desc: "WorldEdit 的可视化界面", mcVersion: "1.21.10" },
    { name: "Axiom", file: "Axiom-5.2.1-for-MC1.21.10.jar", category: "utility", deps: [], depBy: [], desc: "融合 3D 软件功能的世界编辑工具", mcVersion: "1.21.10" },
    { name: "Distant Horizons", file: "DistantHorizons-2.4.5-b-1.21.10-fabric-neoforge.jar", category: "utility", deps: [], depBy: [], desc: "通过简化地形增加视距", mcVersion: "1.21.10" },
    { name: "Fabric Carpet", file: "fabric-carpet-1.21.10-1.4.188+v251016.jar", category: "utility", deps: [], depBy: [], desc: "技术玩家的调试和测试工具", mcVersion: "1.21.10" }
];

const CATEGORIES = { library: '核心库', optimization: '性能优化', gameplay: '玩法机制', decoration: '装饰物品', utility: '实用工具' };
